// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://affiktrpdgtroxgoccra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZmlrdHJwZGd0cm94Z29jY3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDM1OTUsImV4cCI6MjA3NDIxOTU5NX0.kMBBpAz6mtMujLSz3zQaOdGSAqyElm-Xl642Lm_EILo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});